version: '3.5'
services:
  server:
    build: .
    command: yarn dev 
    volumes: 
      - .:/server
  # mongodb:
  #   image: mongo:latest
  #   restart: always
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME:${MONGO_ROOT_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD:${MONGO_ROOT_PASSWORD}
  # mongo:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8001:8001
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME:${MONGO_ROOT_USERNAME}
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD:${MONGO_ROOT_PASSWORD}
  #     - ME_CONFIG_MONGODB_URL:${DB_URI}
